name: Build app, push and run app
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission to Maven wrapper
        run: chmod +x ./mvnw

      - name: Build Spring Boot Application
        run: ./mvnw clean package -DskipTests

      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/stockaroo:latest .

      - name: Push Docker Image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/stockaroo:latest

      - name: Run Docker Container
        run: |
          docker run -d \
          -e DB_CONNECTION_STRING=${{ secrets.DB_CONNECTION_STRING }} \
          -p 8080:8080 \
          ${{ secrets.DOCKER_USERNAME }}/stockaroo:latest

